services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Subugoe\Find\:
    resource: '../Classes/*'

  Subugoe\Find\SignalSlot\Dispatcher:
    public: true

  Subugoe\Find\Service\SolrServiceProvider:
    public: true
